// <auto-generated />
using DemoWebApiProject.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoWebApiProject.Migrations
{
    [DbContext(typeof(GameProgressContext))]
    partial class GameProgressContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("DemoWebApiProject.Entities.GameProgress", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChineseName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("GameId");

                    b.ToTable("GameProgresses");
                });

            modelBuilder.Entity("DemoWebApiProject.Entities.GameProgressOnPlatform", b =>
                {
                    b.Property<int>("GameProgressOnThisPlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BugsAndIssues")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgressOnThisPlatform")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendedMouseSpeed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GameProgressOnThisPlatformId");

                    b.HasIndex("GameId");

                    b.ToTable("GameProgressOnPlatforms");
                });

            modelBuilder.Entity("DemoWebApiProject.Entities.GameProgressOnPlatform", b =>
                {
                    b.HasOne("DemoWebApiProject.Entities.GameProgress", "GameProgress")
                        .WithMany("GameProgressOnPlatforms")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameProgress");
                });

            modelBuilder.Entity("DemoWebApiProject.Entities.GameProgress", b =>
                {
                    b.Navigation("GameProgressOnPlatforms");
                });
#pragma warning restore 612, 618
        }
    }
}
